### ISSUE TITLE
Undefined names in unreferenced_metric.py

### ISSUE THREAD

**Issue by cgsdfc** [liming-vie/RUBER#6]
https://github.com/liming-vie/RUBER/blob/b067e5969c303a2f96da55a1094cd5b37b8900f4/unreferenced_metric.py#L189

There are two undefined names in `unreferenced_metric.py`, namely `reply_sizes` and `query_sizes`.  How to fix them? Thanks.

**Comment by liming-vie** [comment]
Sorry for the trouble, they should be renamed to rsizes and qsizes.

**Comment by cgsdfc** [comment]
ok
