### ISSUE TITLE
Which word2vec embedding did you use?

### ISSUE THREAD

**Issue by cgsdfc** [liming-vie/RUBER#7]
There is a vast number of embeddings nowadays from which I can choose. Which one did you use? Or does it matter?

**Comment by liming-vie** [comment]
Yes it matters. Use the corpus that's nearest to the circumstances of your dialog system is better I think.
But in general cases, just use the model that Google trained is fine.

**Comment by cgsdfc** [comment]
Sorry, I actually did not use this project.
