### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [liming-vie/RUBER#9]
First of all, thanks for your open-source code of this work.
I haven't run the scripts on a particular data set, but I'm curious about the performance that you test on. 
Can you reproduce the results of the experiment in the paper?
Thanks!

**Comment by liming-vie** [comment]
I don't remember the exact result. But it should be worse than that in paper.

**Comment by gmftbyGMFTBY** [comment]
Ok, got it, thank you!
